# Generated by Django 5.1.4 on 2025-01-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_name2_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name2',
        ),
    ]
