# Generated by Django 5.1.1 on 2025-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_category_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='hikaye_kitap',
            field=models.ManyToManyField(blank=True, to='courses.kitap'),
        ),
    ]
