# Generated by Django 5.1.1 on 2025-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_kitap_hikaye_kitap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='summary',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
