# Generated by Django 5.1.4 on 2025-01-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_kitap_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='courses.category'),
        ),
    ]
